// resources/assets/js/components/Field.tsx
import React, {Component} from 'react';

interface FieldProps {
    help?: string,
    errors?: string,
    success?: string
}
export default class Field extends Component<FieldProps, {}> {
    constructor(props) {
        super(props);
    }

    render() {
        let formClass = "form-group";
        if(this.props.errors) {
            formClass += " is-invalid";
        }
        if(this.props.success) {
            formClass += " is-valid";
        }
        return (
            <div>
                <div className={formClass}>
                    {this.props.children}
                    {this.props.help && <small className="form-text text-muted">{this.props.help}</small>}
                    {this.props.errors && <div className="invalid-feedback">{this.props.errors}</div> }
                    {this.props.success && <div className="valid-feedback">{this.props.success}</div>}
                </div>
            </div>
        );
    }

}

// resources/assets/js/components_vue/Field.vue
<template>
    <div class="form-group" :class="{'is-invalid': form.errors.get(name), 'is-valid' : success && form.successful}">
        <slot></slot>
        <small class="form-text text-muted">{{help}}</small>
        <div class="invalid-feedback">{{form.errors.get(name)}}</div>
        <div class="valid-feedback">
            <slot name="valid-feedback"></slot>
        </div>
    </div>
</template>

<script>
    export default {
        props: {
            form: {
                required: true
            },
            name: {
                required: true
            },
            required: {
                default: false
            },
            help: {
                required: false,
                default: ""
            },
            showSuccess: {
                required: false,
                default: "false"
            }
        },

        computed: {
            success(){
                if(this.showSuccess === true){
                    return this.showSuccess;
                } else {
                    return this.showSuccess === "true";
                }
            }
        }
    }
</script>
